#!/bin/csh -fe

if ( "$1" == "-h" || "$1" == "--help" ) then
  echo
  echo "developer: updates Git administration files with developer name"
  echo
  echo "usage:"
  echo "  Management/developer USER"
  echo
  echo "where:"
  echo "  USER is a sourceforge user name"
  echo
  exit
endif

set root = "git.code.sf.net/p/psrchive/code"

if ( "$1" == "" ) then
  echo "Git repository access changed to anonymous"
  git config remote.origin.url git://$root
else if ( "$#" == "1" ) then
  echo "Git repository developer name changed to $1"
  git config remote.origin.url ssh://$1@$root
else if ("$#" == "3" ) then
  echo "Git repository developer name changed to $1"
  echo "Git user name changed to $2"
  echo "Git user email changed to $3"
  git config remote.origin.url ssh://$1@$root
  echo git config user.name "$2"
  git config user.name "$2"
  echo git config user.email "$3"
  git config user.email "$3"
endif
