<?PHP

include ("bpsr.lib.php");
$inst = new bpsr();

# get the list of configurable ibobs
$ibobs = array();
for ($i=0; $i<$inst->ibobs["NUM_IBOB"]; $i++)
{
  $ibobs[$i] = $inst->ibobs["10GbE_CABLE_".$i];
}

?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<?
  $inst->print_head("BPSR | Beam Reconfigure");
?>
<body style='text-align: left;'>
<?

if (isset($_POST["action"]) && ($_POST["action"] == "change"))
{

  $j = 0;
  $new_pwcs = array();
  for ($i=0; $i<count($ibobs); $i++) 
  {
    if (isset($_POST[$ibobs[$i]."_active"]) && ($_POST[$ibobs[$i]."_active"] == "on"))
    {
      $new_pwcs[$j] = $ibobs[$i];
      $j++;
    }
  }
  $num_pwcs = count($new_pwcs);

  # Stop BPSR backend
  $script = "source /home/dada/.bashrc; bpsr_reconfigure.pl -s 2>&1";
  echo "<pre>\n";
  system($script, $rval);
  if ($rval != 0) {
    exit;
  }
  echo "</pre>\n";

  # adjust the bpsr_pwcs.cfg file
  $fptr = fopen(PWC_FILE, "w");
  if (!$fptr) {
    echo "ERROR: could not open PWC config file [".PWC_FILE."] for writing<BR>\n";
    exit;
  }

  fwrite($fptr, "# BPSR PWC Config File\n");
  fwrite($fptr, "# generated by bpsr_reconfig.php on ".date(DADA_TIME_FORMAT, time())."<BR>\n");
  fwrite($fptr, instrument::headerFormat("NUM_PWC", count($new_pwcs))."\n");

  for ($i=0; $i<count($new_pwcs); $i++) {
    fwrite($fptr, instrument::headerFormat("PWC_".$i, $new_pwcs[$i])."\n");
  }

  fclose($fptr);
  
  # re-read SYS_CONFIG file
  unset($inst);
  $inst = new bpsr();

  # Start BPSR backend
  $script = "source /home/dada/.bashrc; bpsr_reconfigure.pl -i 2>&1";
  echo "<pre>\n";
  system($script, $rval);
  if ($rval != 0) {
    exit;
  }
  echo "</pre>\n";

  echo "<script type='text/javascript'>\n";
  echo "  parent.document.location='beam_config.php'\n";
  echo "</script>\n";

}

?>
</body>
</html>
