LOCAL_ROOT := ../../..
include $(LOCAL_ROOT)/include/Makefile.standard

DOCS := Specification.tex

Specification.dvi: layout.eps intro.tex primary.tex secondary.tex summary.tex

include $(LOCAL_ROOT)/include/Makefile.tex

