#-*-Makefile-*- helps emacs recognize this file as a Makefile

##########################################################################
#
# standard Makefile rules for latex stuff
#
##########################################################################

.SUFFIXES: .ps .dvi

# Standard ways of making things

%.ps: %.dvi 
	dvips $< -o $@ 

%.dvi: %.tex
# Get new refs
	latex $*
# Generate tex for em
	bibtex $* ; date
# Tell latex about them
	latex $* 
# Second pass to fix cross-references
	latex $*

# standard targets
# Note, DOCS must be set to a list of .tex files first
DVIS := ${DOCS:.tex=.dvi}
PSS := ${DOCS:.tex=.ps}

all: ps
ps: $(PSS)
dvi: $(DVIS)

.PHONY : clean
clean :
	-rm -f *.aux *.bbl *.blg *.log *.toc

.PHONY : cleanall
cleanall :
	-rm -f *.aux *.bbl *.blg *.log *.toc *.dvi *.ps

%:%.ps
	@echo $@.ps is up-to-date.

