#!/bin/csh
#
# Willem van Straten  1 July 1999
#
# loops n from $2 to $3, running $4 on $1$n

if ( $1 == "" || $2 == "" || $3 == "" || "$4" == "" ) then
	echo usage: $0 prefix start end \'command\' [ssh args]
	echo ssh to \'prefix\'\$n where \$n runs from
	echo \'start\' to \'end\', and run \'command\' in the background
	exit 1
endif

echo Running ssh $5 \'$4\' on $1$2-\>$3

set n = $2
while ( $n <= $3 )
	set nn = `echo $n | awk '{printf ("%02d", $1)}'`
	ssh -x -f $5 $1$nn /bin/csh -c "echo; $4"
	@ n = $n + 1
end

